{
  "name": "async-catch-loader",
  "version": "1.0.0",
  "description": "a webpack loader that captures error of async function",
  "main": "lib/index.js",
  "scripts": {
    "test": "jest  --watchAll"
  },
  "keywords": [
    "loader",
    "webpack",
    "try",
    "catch"
  ],
  "author": "njt",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/parser": "^7.5.0",
    "@babel/preset-env": "^7.5.2",
    "@babel/traverse": "^7.5.0",
    "@babel/types": "^7.5.0",
    "babel-jest": "^24.8.0",
    "babel-polyfill": "^6.26.0",
    "jest": "^24.8.0",
    "loader-utils": "^1.2.3",
    "memory-fs": "^0.4.1",
    "webpack": "^4.35.3"
  }
}
